### ISSUE TITLE
Bot quotes

### ISSUE THREAD

**Issue by eskimo4130** [openra-community/openra-irc_bot#1]
I don't know how Github works. Just some food for thought.

Gatekeeper
"yeah, nah, gg"

Tailix
"ragl training, lol"

Unano
"In a minute, just finishing my kebab"

Happy
"I would like to delay my RAGL games infinitely"

Barf
"BAAARRRRRRRRRRRRRRRRRRRRRRRRF"

Ganon
"K"

**Comment by eskimo4130** [comment]
n/a
"It's still a terrible map"

**Comment by openra-community** [comment]
Done in https://github.com/openra-community/openra-irc_bot/commit/41f08336c8e384f6ab3e5626237d01bd7ce3febe with some changes and - Ganon & Barf
